[package]
name = "bleps-dedup"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
syn = { version = "2.0.39", features = ["full"] }
darling = "0.20.3"

[features]
generate-async = []
